apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mnist
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vic614/argo-mnist.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: mnist
  syncOptions:
  - CreateNamespace=true